#pragma checksum "..\..\..\Main\Base.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7BED9E87CD57A9C67335FE81C1E919867C452FE3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Poli.Makro.Converters;
using Poli.Makro.States.Clipboard;
using Poli.Makro.States.Color;
using Poli.Makro.States.JSONXMLXAMLRSS;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Interactivity;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Poli.Makro.Main {
    
    
    /// <summary>
    /// Base
    /// </summary>
    public partial class Base : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 52 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl SideBarTabControl;
        
        #line default
        #line hidden
        
        
        #line 146 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem ColorsSideBarTab;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton ColorLibrary;
        
        #line default
        #line hidden
        
        
        #line 188 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton DominantColorExtractor;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem CodesSideBarTab;
        
        #line default
        #line hidden
        
        
        #line 232 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton CodeLibrary;
        
        #line default
        #line hidden
        
        
        #line 267 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControl;
        
        #line default
        #line hidden
        
        
        #line 270 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl ClipbardState;
        
        #line default
        #line hidden
        
        
        #line 284 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl ColorsTab;
        
        #line default
        #line hidden
        
        
        #line 295 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl CodesTab;
        
        #line default
        #line hidden
        
        
        #line 316 "..\..\..\Main\Base.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Title;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Poli.Makro;component/main/base.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Main\Base.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 16 "..\..\..\Main\Base.xaml"
            ((Poli.Makro.Main.Base)(target)).Loaded += new System.Windows.RoutedEventHandler(this.MainWindow_OnLoaded);
            
            #line default
            #line hidden
            
            #line 16 "..\..\..\Main\Base.xaml"
            ((Poli.Makro.Main.Base)(target)).Closing += new System.ComponentModel.CancelEventHandler(this.MainWindow_OnClosing);
            
            #line default
            #line hidden
            
            #line 16 "..\..\..\Main\Base.xaml"
            ((Poli.Makro.Main.Base)(target)).SizeChanged += new System.Windows.SizeChangedEventHandler(this.AnaPencere1_SizeChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.SideBarTabControl = ((System.Windows.Controls.TabControl)(target));
            
            #line 56 "..\..\..\Main\Base.xaml"
            this.SideBarTabControl.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.SideBarTabControl_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 81 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Expander)(target)).Expanded += new System.Windows.RoutedEventHandler(this.SidebarMenuItemExpanded);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 85 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Primitives.ToggleButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.MenuButtonIsChecked);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 93 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Expander)(target)).Expanded += new System.Windows.RoutedEventHandler(this.SidebarMenuItemExpanded);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 97 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Primitives.ToggleButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.MenuButtonIsChecked);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 105 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Expander)(target)).Expanded += new System.Windows.RoutedEventHandler(this.SidebarMenuItemExpanded);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 109 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Primitives.ToggleButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.MenuButtonIsChecked);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 117 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Expander)(target)).Expanded += new System.Windows.RoutedEventHandler(this.SidebarMenuItemExpanded);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 121 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Primitives.ToggleButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.MenuButtonIsChecked);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 129 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Expander)(target)).Expanded += new System.Windows.RoutedEventHandler(this.SidebarMenuItemExpanded);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 133 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Primitives.ToggleButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.MenuButtonIsChecked);
            
            #line default
            #line hidden
            return;
            case 13:
            this.ColorsSideBarTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 14:
            
            #line 171 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Expander)(target)).Expanded += new System.Windows.RoutedEventHandler(this.SidebarMenuItemExpanded);
            
            #line default
            #line hidden
            return;
            case 15:
            this.ColorLibrary = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            
            #line 175 "..\..\..\Main\Base.xaml"
            this.ColorLibrary.Checked += new System.Windows.RoutedEventHandler(this.ColorLibrary_Checked);
            
            #line default
            #line hidden
            return;
            case 16:
            
            #line 184 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Expander)(target)).Expanded += new System.Windows.RoutedEventHandler(this.SidebarMenuItemExpanded);
            
            #line default
            #line hidden
            return;
            case 17:
            this.DominantColorExtractor = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            
            #line 188 "..\..\..\Main\Base.xaml"
            this.DominantColorExtractor.Checked += new System.Windows.RoutedEventHandler(this.DominantColorExtractor_Checked);
            
            #line default
            #line hidden
            return;
            case 18:
            this.CodesSideBarTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 19:
            
            #line 228 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Expander)(target)).Expanded += new System.Windows.RoutedEventHandler(this.SidebarMenuItemExpanded);
            
            #line default
            #line hidden
            return;
            case 20:
            this.CodeLibrary = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            
            #line 232 "..\..\..\Main\Base.xaml"
            this.CodeLibrary.Checked += new System.Windows.RoutedEventHandler(this.CodeLibrary_Checked);
            
            #line default
            #line hidden
            return;
            case 21:
            this.TabControl = ((System.Windows.Controls.TabControl)(target));
            return;
            case 22:
            this.ClipbardState = ((System.Windows.Controls.TabControl)(target));
            return;
            case 23:
            this.ColorsTab = ((System.Windows.Controls.TabControl)(target));
            return;
            case 24:
            this.CodesTab = ((System.Windows.Controls.TabControl)(target));
            return;
            case 25:
            
            #line 309 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.side);
            
            #line default
            #line hidden
            return;
            case 26:
            this.Title = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            
            #line 321 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Border_FareSolTıkBasıldığında);
            
            #line default
            #line hidden
            
            #line 322 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Border)(target)).PreviewMouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.Border_ÖnizlemeFareSolTıkKalktığında);
            
            #line default
            #line hidden
            
            #line 323 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Border)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Border_ÖnizlemeFareSolTıkBastığında);
            
            #line default
            #line hidden
            
            #line 324 "..\..\..\Main\Base.xaml"
            ((System.Windows.Controls.Border)(target)).PreviewMouseMove += new System.Windows.Input.MouseEventHandler(this.Border_ÖnizlemeFareyleTaşıma);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

