#pragma checksum "..\..\..\..\States\Clipboard\ClipboardRecords.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "BC0989279D5D29E073037DE49711701AC9FB1241"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Poli.Makro.Converters;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Poli.Makro.States.Clipboard {
    
    
    /// <summary>
    /// ClipboardRecords
    /// </summary>
    public partial class ClipboardRecords : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 268 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControl;
        
        #line default
        #line hidden
        
        
        #line 275 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView Records;
        
        #line default
        #line hidden
        
        
        #line 282 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid SaveGrid;
        
        #line default
        #line hidden
        
        
        #line 293 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border SaveRecords;
        
        #line default
        #line hidden
        
        
        #line 306 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SaveRecordsTitle;
        
        #line default
        #line hidden
        
        
        #line 346 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MagnetGrid;
        
        #line default
        #line hidden
        
        
        #line 370 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox t;
        
        #line default
        #line hidden
        
        
        #line 419 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton Magnet;
        
        #line default
        #line hidden
        
        
        #line 426 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton SaveRecordsTB;
        
        #line default
        #line hidden
        
        
        #line 433 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton ClearRecord;
        
        #line default
        #line hidden
        
        
        #line 454 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox HistoryComboBox;
        
        #line default
        #line hidden
        
        
        #line 466 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView HistoryRecords;
        
        #line default
        #line hidden
        
        
        #line 486 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PetternsListGrid;
        
        #line default
        #line hidden
        
        
        #line 491 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView PetternGroups;
        
        #line default
        #line hidden
        
        
        #line 504 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView Petterns;
        
        #line default
        #line hidden
        
        
        #line 512 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid AddPetternGrid;
        
        #line default
        #line hidden
        
        
        #line 523 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border AddPetternn;
        
        #line default
        #line hidden
        
        
        #line 536 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PetternGroupsComboBox;
        
        #line default
        #line hidden
        
        
        #line 561 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddPetternTitle;
        
        #line default
        #line hidden
        
        
        #line 584 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddPettern;
        
        #line default
        #line hidden
        
        
        #line 619 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid AddPetternGroupGrid;
        
        #line default
        #line hidden
        
        
        #line 644 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddPetternGroupTitle;
        
        #line default
        #line hidden
        
        
        #line 695 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton SavePetternTB;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Poli.Makro;component/states/clipboard/clipboardrecords.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 4:
            this.TabControl = ((System.Windows.Controls.TabControl)(target));
            
            #line 268 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            this.TabControl.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.TabControl_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.Records = ((System.Windows.Controls.ListView)(target));
            return;
            case 6:
            this.SaveGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 7:
            
            #line 283 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveRecordsClose);
            
            #line default
            #line hidden
            return;
            case 8:
            this.SaveRecords = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.SaveRecordsTitle = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            
            #line 324 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveAsNewTitleAndClean);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 332 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveAsAndClose);
            
            #line default
            #line hidden
            return;
            case 12:
            this.MagnetGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 13:
            
            #line 347 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveRecordsClose);
            
            #line default
            #line hidden
            return;
            case 14:
            this.t = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            
            #line 388 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveAsNewTitleAndClean);
            
            #line default
            #line hidden
            return;
            case 16:
            
            #line 396 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveAsAndClose);
            
            #line default
            #line hidden
            return;
            case 17:
            this.Magnet = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 18:
            this.SaveRecordsTB = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            
            #line 428 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            this.SaveRecordsTB.Checked += new System.Windows.RoutedEventHandler(this.SaveRecordsChecked);
            
            #line default
            #line hidden
            
            #line 428 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            this.SaveRecordsTB.Unchecked += new System.Windows.RoutedEventHandler(this.SaveRecordsClose);
            
            #line default
            #line hidden
            return;
            case 19:
            this.ClearRecord = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            
            #line 435 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            this.ClearRecord.Click += new System.Windows.RoutedEventHandler(this.ClearRecords);
            
            #line default
            #line hidden
            return;
            case 20:
            this.HistoryComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 459 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            this.HistoryComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.HistoryComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 21:
            this.HistoryRecords = ((System.Windows.Controls.ListView)(target));
            return;
            case 22:
            this.PetternsListGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 23:
            this.PetternGroups = ((System.Windows.Controls.ListView)(target));
            
            #line 496 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            this.PetternGroups.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.PetternGroups_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 24:
            this.Petterns = ((System.Windows.Controls.ListView)(target));
            return;
            case 25:
            this.AddPetternGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            
            #line 513 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SavePetternClose);
            
            #line default
            #line hidden
            return;
            case 27:
            this.AddPetternn = ((System.Windows.Controls.Border)(target));
            return;
            case 28:
            this.PetternGroupsComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 541 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            this.PetternGroupsComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.HistoryComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 29:
            
            #line 549 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Primitives.ToggleButton)(target)).Click += new System.Windows.RoutedEventHandler(this.AddNewPetternGroup);
            
            #line default
            #line hidden
            return;
            case 30:
            this.AddPetternTitle = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.AddPettern = ((System.Windows.Controls.TextBox)(target));
            return;
            case 32:
            
            #line 604 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SavePettern);
            
            #line default
            #line hidden
            return;
            case 33:
            this.AddPetternGroupGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 34:
            
            #line 620 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveRecordsClose);
            
            #line default
            #line hidden
            return;
            case 35:
            this.AddPetternGroupTitle = ((System.Windows.Controls.TextBox)(target));
            return;
            case 36:
            
            #line 663 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveGroup);
            
            #line default
            #line hidden
            return;
            case 37:
            
            #line 673 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveGroupCancel);
            
            #line default
            #line hidden
            return;
            case 38:
            this.SavePetternTB = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            
            #line 696 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            this.SavePetternTB.Checked += new System.Windows.RoutedEventHandler(this.SavePetternChecked);
            
            #line default
            #line hidden
            
            #line 696 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            this.SavePetternTB.Unchecked += new System.Windows.RoutedEventHandler(this.SavePetternClose);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 124 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteRecord);
            
            #line default
            #line hidden
            break;
            case 2:
            
            #line 125 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CopyRecord);
            
            #line default
            #line hidden
            break;
            case 3:
            
            #line 126 "..\..\..\..\States\Clipboard\ClipboardRecords.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveAsRecord);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

