#pragma checksum "..\..\..\..\States\Color\ColorLib.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "FEB4B8B7E27CB9654047BF1214005B75E367EF5C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Loaders;
using Poli.Makro.Converters;
using Poli.Makro.Core.Helpers.RichTextBox;
using Poli.Makro.States.Code;
using Poli.Makro.States.Color;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Interactivity;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Xceed.Wpf.Toolkit;
using Xceed.Wpf.Toolkit.Chromes;
using Xceed.Wpf.Toolkit.Core.Converters;
using Xceed.Wpf.Toolkit.Core.Input;
using Xceed.Wpf.Toolkit.Core.Media;
using Xceed.Wpf.Toolkit.Core.Utilities;
using Xceed.Wpf.Toolkit.Panels;
using Xceed.Wpf.Toolkit.Primitives;
using Xceed.Wpf.Toolkit.PropertyGrid;
using Xceed.Wpf.Toolkit.PropertyGrid.Attributes;
using Xceed.Wpf.Toolkit.PropertyGrid.Commands;
using Xceed.Wpf.Toolkit.PropertyGrid.Converters;
using Xceed.Wpf.Toolkit.PropertyGrid.Editors;
using Xceed.Wpf.Toolkit.Zoombox;


namespace Poli.Makro.States.Color {
    
    
    /// <summary>
    /// ColorLib
    /// </summary>
    public partial class ColorLib : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\..\States\Color\ColorLib.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Poli.Makro.States.Color.ColorLib CodeLibUC;
        
        #line default
        #line hidden
        
        
        #line 190 "..\..\..\..\States\Color\ColorLib.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControl;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\..\..\States\Color\ColorLib.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CodeLibListSelectGrid;
        
        #line default
        #line hidden
        
        
        #line 241 "..\..\..\..\States\Color\ColorLib.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView ColorGroupsListView;
        
        #line default
        #line hidden
        
        
        #line 360 "..\..\..\..\States\Color\ColorLib.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddColorTitle;
        
        #line default
        #line hidden
        
        
        #line 398 "..\..\..\..\States\Color\ColorLib.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Color;
        
        #line default
        #line hidden
        
        
        #line 443 "..\..\..\..\States\Color\ColorLib.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Xceed.Wpf.Toolkit.ColorCanvas _colorPicker;
        
        #line default
        #line hidden
        
        
        #line 484 "..\..\..\..\States\Color\ColorLib.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton AddColor;
        
        #line default
        #line hidden
        
        
        #line 493 "..\..\..\..\States\Color\ColorLib.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView ColorsListView;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Poli.Makro;component/states/color/colorlib.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\States\Color\ColorLib.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.CodeLibUC = ((Poli.Makro.States.Color.ColorLib)(target));
            return;
            case 2:
            this.TabControl = ((System.Windows.Controls.TabControl)(target));
            return;
            case 3:
            this.CodeLibListSelectGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            
            #line 232 "..\..\..\..\States\Color\ColorLib.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddColorGroupBtn);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ColorGroupsListView = ((System.Windows.Controls.ListView)(target));
            return;
            case 6:
            this.AddColorTitle = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.Color = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this._colorPicker = ((Xceed.Wpf.Toolkit.ColorCanvas)(target));
            return;
            case 9:
            this.AddColor = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 10:
            this.ColorsListView = ((System.Windows.Controls.ListView)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

